<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="eiger.td.teradata.com" name="com.teradata.tempto.examples.ExampleSshClientUsage" tests="3" failures="1" timestamp="5 Oct 2015 17:31:56 GMT" time="7.499" errors="1">
  <testcase name="sshClientUsage" time="2.516" classname="com.teradata.tempto.examples.ExampleSshClientUsage">
    <error type="java.lang.RuntimeException" message="com.jcraft.jsch.JSchException: Auth fail">
      <![CDATA[java.lang.RuntimeException: com.jcraft.jsch.JSchException: Auth fail
	at com.teradata.tempto.internal.ssh.JSchSshClient.upload(JSchSshClient.java:98)
	at com.teradata.tempto.examples.ExampleSshClientUsage.sshClientUsage(ExampleSshClientUsage.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
Caused by: com.jcraft.jsch.JSchException: Auth fail
	at com.jcraft.jsch.Session.connect(Session.java:512)
	at com.jcraft.jsch.Session.connect(Session.java:183)
	at com.teradata.tempto.internal.ssh.JSchSshClient.getActiveSession(JSchSshClient.java:78)
	at com.teradata.tempto.internal.ssh.JSchSshClient.upload(JSchSshClient.java:88)
	... 26 more
]]>
    </error>
  </testcase> <!-- sshClientUsage -->
  <testcase name="dynamicSshClient" time="2.009" classname="com.teradata.tempto.examples.ExampleSshClientUsage"/>
  <testcase name="longRunningCommandTimeout" time="2.974" classname="com.teradata.tempto.examples.ExampleSshClientUsage">
    <failure type="java.lang.AssertionError" message="
Expecting:
 &lt;&quot;com.jcraft.jsch.JSchException: Auth fail&quot;&gt;
to contain:
 &lt;&quot;did not finish within given timeout&quot;&gt; ">
      <![CDATA[java.lang.AssertionError: 
Expecting:
 <"com.jcraft.jsch.JSchException: Auth fail">
to contain:
 <"did not finish within given timeout"> 
	at com.teradata.tempto.examples.ExampleSshClientUsage.longRunningCommandTimeout(ExampleSshClientUsage.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at com.teradata.tempto.runner.TemptoRunner.run(TemptoRunner.java:81)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:59)
	at com.teradata.tempto.runner.TemptoRunner.runTempto(TemptoRunner.java:47)
	at com.teradata.tempto.examples.TemptoExamples.main(TemptoExamples.java:30)
]]>
    </failure>
  </testcase> <!-- longRunningCommandTimeout -->
</testsuite> <!-- com.teradata.tempto.examples.ExampleSshClientUsage -->
